name: bunqdesktop
base: core18
version: '0.9.8'
summary: The unofficial, free and open source desktop application for the bunq API
description: The unofficial, free and open source desktop application for the bunq API

grade: edge
confinement: strict
parts:
    my-part:
        plugin: nil
